spring:
  datasource:
    url: jdbc:postgresql://ep-wispy-violet-53823986.us-east-2.aws.neon.fl0.io:5432/db-test
    username: fl0user
    password: COZL8ANhrT4G
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
hibernate:
  show_sql: true
  format_sql: true
logging:
  level:
    org.springframework.security: TRACE
api:
  security:
    token:
      secret-key:
        "G2J5V^>4NgQTjH}5DQ5^4#M~'WS05b,pX-[=,+bp#z{|=x+E"
      issuer:
        "todo-api"